### ISSUE TITLE
Execution failed for task ':flutter_email_sender:compileReleaseKotlin'

### ISSUE THREAD

**Issue by Grimmnir** [sidlatau/flutter_email_sender#101] opened 2023-09-22 22:09 UTC
Hi,

trying to create a signed bundle I recently always get the following error:

`Execution failed for task ':flutter_email_sender:compileReleaseKotlin'.
 'compileReleaseJavaWithJavac' task (current target is 1.8) and 'compileReleaseKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain`

not sure how to fix it. Any suggestions?

**Comment by sidlatau** [comment] 2023-09-23 06:00
I release v6.0.2, please check if the issue is fixed in that version.

**Comment by Grimmnir** [comment] 2023-09-24 13:02
Issue resolved, thank you vey much v6.0.2 fixed it

**Closed** 2023-09-24 16:36 UTC
